# INTRODUCTION

## Say "Hello, World!" With Python

In [1]:
if __name__ == '__main__':
    print("Hello, World!")

Hello, World!


## Python If-Else

In [7]:
#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input().strip())
if n % 2 != 0:
    print("Weird")
elif n % 2 == 0:
    if 2 <= n <= 5:
        print("Not Weird")
    elif 6 <= n <= 20:
        print("Weird")
    elif n > 20:
        print("Not Weird")

 3


Weird


## Arithmetic Operators

In [14]:
if __name__ == '__main__':
    a = int(input())
    b = int(input())
    print(a + b)
    print(a - b)
    print(a * b)

 3
 2


5
1
6


## Python: Division

In [16]:
if __name__ == '__main__':
    a = int(input())
    b = int(input())
    print(a // b)
    print(a / b)

 4
 3


1
1.3333333333333333


## Loops

In [20]:
if __name__ == '__main__':
    n = int(input())
    
for i in range(0,n):
    print (i ** 2)

 5


0
1
4
9
16


## Write a function

In [22]:
def is_leap(year):
    leap = False
    if (year % 4 == 0 and year % 100 != 0) or (year % 100 == 0 and year % 400 == 0):
        leap = True
        
    return leap

## Print Function

In [24]:
if __name__ == '__main__':
    n = int(input())
    for i in range(n): print(i+1, end='')

 3


123

# Basic Data Types

## List Comprehensions

In [28]:
if __name__ == '__main__':
    x = int(input())
    y = int(input())
    z = int(input())
    n = int(input())
coordinates = [[i,j,k] for i in range(x+1) for j in range(y +1) for k in range(z+1) if i+j+k != n]

                
print(coordinates)

 1
 1
 1
 2


[[0, 0, 0], [0, 0, 1], [0, 1, 0], [1, 0, 0], [1, 1, 1]]


## Find the Runner-Up Score!

In [36]:
if __name__ == '__main__':
    n = int(input())
    arr = map(int, input().split())
    scores = list(arr)
    for i in scores:
        if i == n:
            print(i)

 5
 2 3 6 6 5


5


In [38]:
if __name__ == '__main__':
    n = int(input())
    arr = map(int, input().split())
    scores = list(set(arr))
    scores.sort()
    print(scores[-2])

 5
 2 3 6 6 5


5


## Nested Lists

In [44]:
if __name__ == '__main__':
    students = []
    for _ in range(int(input())):
        name = input()
        score = float(input())
        students.append([name, score])
only_scores = [x[1] for x in students]
minimum_score = sorted(set(only_scores))
students_min = sorted([y[0] for y in students if y[1]==minimum_score[1]])
[print(i) for i in students_min]

 5
 Harry
 37.21
 Berry
 37.21
 Tina
 37.2
 Akriti
 41
 Harsh
 39


Berry
Harry


[None, None]

## Finding the percentage

In [46]:
if __name__ == '__main__':
    n = int(input())
    student_marks = {}
    for _ in range(n):
        name, *line = input().split()
        scores = list(map(float, line))
        student_marks[name] = scores
    query_name = input()
    prv_name = student_marks[query_name]
    average = sum(prv_name)/3
    # We will print the average with 2 places after decimal
    print("%.2f" % average)

 3
 Krishna 67 68 69
 Arjun 70 98 63
 Malika 52 56 60
 Malika


56.00


## Lists

In [48]:
if __name__ == '__main__':
    N = int(input())
    li = []
    for i in range(N):
        x = list(input().split()) # I used split in order to split the inputs into a list
        if x[0] == "insert":
            li.insert(int(x[1]), int(x[2]))
        if x[0] == "remove":
            li.remove(int(x[1]))
        if x[0] == "append":
            li.append(int(x[1]))
        if x[0] == "sort":
            li.sort()
        if x[0] == "pop":
            li.pop()
        if x[0] == "reverse":
            li.reverse()
        if x[0] == "print":
            print(li)

 12
 insert 0 5
 insert 1 10
 insert 0 6
 print


[6, 5, 10]


 remove 6
 append 9
 append 1 
 sort
 print


[1, 5, 9, 10]


 pop
 reverse
 print


[9, 5, 1]


## Tuples

In [50]:
if __name__ == '__main__':
    n = int(input())
    integer_list = map(int, input().split())
    t = tuple(integer_list)
    print(hash(t))

 2
 1 2


-3550055125485641917


# Strings

## sWAP cASE

In [57]:
def swap_case(s):
    return s.swapcase()

## What's Your Name?

In [59]:
#
# Complete the 'print_full_name' function below.
#
# The function is expected to return a STRING.
# The function accepts following parameters:
#  1. STRING first
#  2. STRING last
#

def print_full_name(first, last):
    # Write your code here
    print(f"Hello {first} {last}! You just delved into python.")

## String Split and Join

In [61]:
def split_and_join(line):
    # write your code here
    l = line
    s = l.split(" ")
    return "-".join(s)
if __name__ == '__main__':
    line = input()
    result = split_and_join(line)
    print(result)

 this is a string


this-is-a-string


## Mutations

In [63]:
def mutate_string(string, position, character):
    return string[:position] + character + string[position+1:]

## Find a string

In [74]:
def count_substring(string, sub_string):
    return sum(string[i:].startswith(sub_string) for i in range(len(string)))

## String Validators

In [76]:
if __name__ == '__main__':
    s = input()
string = list(s)

alphan = False
alpha = False
dig = False
lower = False
upper = False

for i in string:
    alphan  = alphan or i.isalnum()
    alpha = alpha or i.isalpha()
    dig = dig or i.isdigit()
    lower = lower or i.islower()
    upper = upper or i.isupper()

print(alphan)
print(alpha)
print(dig)
print(lower)
print(upper)

 qA2


True
True
True
True
True


## Text Alignment

In [78]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
thick = int(input())
filler = "H"

for i in range(thick): # to create the top arrow, by increasing the width
    print((filler*i).rjust(thick-1) + filler + (filler*i).ljust(thick-1))
for i in range(thick+1): #to create the top column
    print((filler*thick).center(thick*2) + (filler*thick).center(thick*6))
for i in range((thick+1)//2): # to create the middle, by printing as 5 times the thickness
    print((filler*thick*5).center(thick*6))
for i in range(thick+1): #to create the bottom column, as the top column
    print((filler*thick).center(thick*2)+(filler*thick).center(thick*6))
for i in range(thick): #to create the bottom arrow, by decreasing the width
    print(((filler*(thick-i-1)).rjust(thick)+filler+(filler*(thick-i-1)).ljust(thick)).rjust(thick*6))

 5


    H    
   HHH   
  HHHHH  
 HHHHHHH 
HHHHHHHHH
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
                    HHHHHHHHH 
                     HHHHHHH  
                      HHHHH   
                       HHH    
                        H     


## Text Wrap

In [80]:
def wrap(string, max_width):
    final = textwrap.fill(string, max_width)
    return final

## Designer Door Mat

In [82]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
# We will use the "center" function in order to put the ".|." in the center as well as the "WELCOME"
N,M = list(map(int,input().split()))
j = 1
for i in range(N):
    if i < N//2:
        print((".|."*j).center(M,"-")) # in order to create the upper part
        j += 2 # it's increasing by 2 every time
    elif i == N//2: # in order to create the middle part
        print("WELCOME".center(M,"-"))
    elif i > N//2: # in order to create the bottom part
        j -= 2 # it's decreasing by 2 every time
        print((".|."*j).center(M,"-"))

 7 21


---------.|.---------
------.|..|..|.------
---.|..|..|..|..|.---
-------WELCOME-------
---.|..|..|..|..|.---
------.|..|..|.------
---------.|.---------


## String Formatting

In [86]:
def print_formatted(number):
    # your code goes here
    binary = format(number,"b")
    size = len(binary)
    for i in range(1,n+1):
        octal = format(i,"o")
        hexad = format(i,"x")
        bina = format(i,"b")
        
        print(str(i).rjust(size),str(octal).rjust(size),str(hexad.upper()).rjust(size),str(bina).rjust(size))

## Alphabet Rangoli

In [88]:
def print_rangoli(size):
    # your code goes here
    order = "-".join(chr(char) for char in reversed(range(ord("a"), ord("a")+size)))
    # we reverse the order of the alphabet until the nth letter
    l = []
    for i in range(1, size*2, 2):
        # we are slicing the string and we connect it with its reverse
        line = f"{order[:i]}{order[:i-1][::-1]}"
        l.append(f'{line:-^{size * 4 - 3}}')
        print(l[-1]) # we print the list in reverse
    print('\n'.join(reversed(l[:-1])))

## Capitalize!

In [90]:
# Complete the solve function below.
def solve(s):
    return " ".join([fullname.capitalize() for fullname in s.split(" ")])


## The Minion Game

In [92]:
def minion_game(string):
    # your code goes here
    Stuart = Kevin = 0
    length = len(string)
    Vowels = "AEIOU"
    for i in range(length):
        if string[i] in Vowels:
            Kevin += length - i
        else:
            Stuart += length - i
    if Kevin < Stuart:
        print("Stuart", str(Stuart))
    elif Kevin > Stuart:
        print("Kevin", str(Kevin))
    else:
        print("Draw")

## Merge the Tools!

In [95]:
def merge_the_tools(string, k):
    # your code goes here
    a = len(string)//k
    for i in range(a):
        print("".join(dict.fromkeys(string[i*k:(i*k)+k])))

# Sets

## Introduction to Sets

In [107]:
def average(array):
    # your code goes here
    a = set(arr)
    average = sum(a)/len(a)
    return(round(average, 3))

## No Idea!

In [109]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
N,M = input().split()
array = input().split()
hap = 0
A = set(input().split())
B = set(input().split())

for i in array:
    if i in A:
        hap += 1
    elif i in B:
        hap -= 1
    else:
        hap = hap

print(hap)

 3 2
 1 5 3
 3 1
 5 7


1


## Symmetric Difference

In [111]:
# Enter your code here. Read input from STDIN. Print output to STDOUT
M = int(input())
setM = set(map(int, input().split()))
N = int(input())
setN = set(map(int, input().split()))

symmetric_difference = setM.symmetric_difference(setN)

sort = sorted(symmetric_difference)
for i in sort:
    print(i)

 4
 2 4 5 9
 4
 2 4 11 12


5
9
11
12


## Set .add()

In [113]:
N = int(input())
stamps_countries = set()

for i in range(N):
    stamps_countries.add(input())
print(len(stamps_countries))

 7
 UK
 China
 USA
 France
 New Zeland
 UK
 France


5


## Set .discard(), .remove() & .pop()

In [115]:
n = int(input())
s = set(map(int, input().split()))
N = int(input())
for i in range(N):
    commands = input().split()
    if commands[0] == "pop":
        s.pop()
    elif commands[0] == "remove":
        s.remove(int(commands[1]))
    else:
        s.discard(int(commands[1]))
print(sum(s))

 9
 1 2 3 4 5 6 7 8 9
 10
 pop
 remove 9
 discard 9
 discard 8
 remove 7
 pop
 discard 6
 remove 5
 pop
 discard 5


4


## Set .union() Operation

In [117]:
n = int(input())
English = set(map(int, input().split()))
b = int(input())
French = set(map(int, input().split()))

print(len(English.union(French)))

 9
 1 2 3 4 5 6 7 8 9
 9
 10 1 2 3 11 21 55 6 8


13


## Set .intersection() Operation

In [119]:
n = int(input())
English = set(map(int, input().split()))
b = int(input())
French = set(map(int, input().split()))
print(len(English & French))

 9
 1 2 3 4 5 6 7 8 9
 9
 10 1 2 3 11 21 55 6 8


5


## Set .difference() Operation

In [121]:
n = int(input())
English = set(map(int, input().split()))
b = int(input())
French = set(map(int, input().split()))
print(len(English.difference(French)))

 9
 1 2 3 4 5 6 7 8 9
 9
 10 1 2 3 11 21 55 6 8


4


## Set .symmetric_difference() Operation

In [123]:
n = int(input())
English = set(map(int, input().split()))
b = int(input())
French = set(map(int, input().split()))
print(len(English.symmetric_difference(French)))

 9
 1 2 3 4 5 6 7 8 9
 9
 10 1 2 3 11 21 55 6 8


8


## Set Mutations

In [129]:
elements_A = int(input())
setA = set(map(int, input().split()))
other_sets = int(input())
for i in range(other_sets):
    operation_name = input().split()
    randomset = set(map(int, input().split()))
    if operation_name[0] == "update":
        setA.update(randomset)
    elif operation_name[0] == "intersection_update":
        setA.intersection_update(randomset)
    elif operation_name[0] == "difference_update":
        setA.difference_update(randomset)
    else:
        setA.symmetric_difference_update(randomset)

print(sum(setA))

 16
 1 2 3 4 5 6 7 8 9 10 11 12 13 14 24 52
 4
 intersection_update 10
 2 3 5 6 8 9 1 4 7 11
 update 2
 55 66
 symmetric_difference_update 5
 22 7 35 62 58
 difference_update 7
 11 22 35 55 58 62 66


38


## The Captain's Room

In [134]:
from collections import Counter

K = int(input())
room_number = list(map(int, input().split()))
repeat_room = Counter(room_number)
for i, repeats in repeat_room.items():
    if repeats == 1:
        print(i)
        break

 5
 1 2 3 6 5 4 4 2 5 3 6 1 6 5 3 2 4 1 2 5 1 4 3 6 8 4 3 1 5 6 2 


8


## Check Subset

In [136]:
T = int(input())
for i in range(T):
    elementsA = int(input())
    A = set(map(int, input().split()))
    elementsB = int(input())
    B = set(map(int, input().split()))
    print(A <= B)

 3
 5
 1 2 3 5 6
 9
 9 8 5 6 3 2 1 4 7


True


 1
 2
 5
 3 6 5 4 1


False


 7
 1 2 3 5 6 8 9
 3
 9 8 2


False


## Check Strict Superset

In [147]:
A = set(map(int, input().split()))
n = int(input())
x = True
for i in range(n):
    other = set(map(int, input().split()))
    if not A.issuperset(other):
        x = False
        break
print(x)

 1 2 3 4 5 6 7 8 9 10 11 12 23 45 84 78
 2
 1 2 3 4 5
 100 11 12


False


# Collections

## collections.Counter()

In [7]:
from collections import Counter

shoes = int(input())
sizes = Counter(list(map(int, input().split())))
customers = int(input())
money = 0
for i in range(customers):
    shoe_size, x = map(int, input().split())
    if sizes[shoe_size]:
        money += x
        sizes[shoe_size] -= 1

print(money)

 10
 2 3 4 5 6 7 8 7 6 5 18
 6
 6 55
 6 45
 6 55
 4 40
 18 60
 10 50


200


## DefaultDict Tutorial

In [9]:
from collections import defaultdict

A = defaultdict(list)
n, m = list(map(int, input().split()))
for i in range(n):
    A[input()].append(i+1)

for x in range(m):
    B = input()
    if B in A.keys():
        print(*A[B])
    else:
        print(-1)

 5 2
 a
 a
 b
 a
 b
 a


1 2 4


 b


3 5


## Collections.namedtuple()

In [11]:
from collections import namedtuple
students = int(input())
columns = namedtuple("columns", input().split())
# we get the input for each student and we extract the MARKS an we sum them.
# we find the average and we print it to 2 decimal places
print(f"{sum(int(columns(*input().split()).MARKS)for i in range(students))/students:.2f}")

 5
 ID         MARKS      NAME       CLASS
 1          97         Raymond    7
 2          50         Steven     4
 3          91         Adrian     9
 4          72         Stewart    5
 5          80         Peter      6


78.00


## Collections.OrderedDict()

In [13]:
from collections import OrderedDict

n_items = int(input())
ordered_dictionary = OrderedDict()
for i in range(n_items):
    item, price = input().rsplit(" ", 1)
    ordered_dictionary[item] = ordered_dictionary.get(item, 0) + int(price)

for item, price in ordered_dictionary.items():
    print(f"{item} {price}")

 9
 BANANA FRIES 12
 POTATO CHIPS 30
 APPLE JUICE 10
 CANDY 5
 APPLE JUICE 10
 CANDY 5
 CANDY 5
 CANDY 5
 POTATO CHIPS 30


BANANA FRIES 12
POTATO CHIPS 60
APPLE JUICE 20
CANDY 20


## Word Order

In [15]:
from collections import Counter
n = int(input())

wordl = [list(map(str, input().split()))for i in range(n)]
    
x = [j[0]for j in wordl]


print(len(Counter(x).keys()))
frequencies = list(Counter(x).values())
str_fr = " ".join([str(y) for y in frequencies])
print(str_fr)

 4
 bcdef
 abcdefg
 bcde
 bcdef


3
2 1 1


## Collections.deque() 

In [20]:
from collections import deque
d = deque()
n = int(input())
for i in range(n):
    method = input().split()
    if method[0] == "append":
        d.append(method[1])
    elif method[0] == "pop":
        d.pop()
    elif method[0] == "popleft":
        d.popleft()
    else:
        d.appendleft(method[1])

print(" ".join(d))

 6
 append 1
 append 2
 append 3
 appendleft 4
 pop
 popleft


1 2


## Company Logo

In [25]:
import math
import os
import random
import re
import sys
from collections import Counter



if __name__ == '__main__':
    s = input() #company name in lowercase
    sort = sorted(s)
    common = Counter(list(sort))
    for i, x in common.most_common(3):
        print(i, x)
    

 aabbbccde


b 3
a 2
c 2


## Piling Up!

In [30]:
from collections import deque
T = int(input())
for i in range(T):
    n = int(input())
    d = deque(list(map(int, input().split())))
    x = 2**31
    for j in range(len(d)):
        if d[0]>=d[len(d)-1] and d[0]<=x:
            x = d.popleft()
        elif d[len(d)-1]<=x:
            x = d.pop()
        else:
            print("No")
            break
    if len(d) == 0:
        print("Yes")
    

 2
 6
 4 3 2 1 3 4


Yes


 3
 1 3 2


No


# Date and Time

## Calendar Module

In [34]:
import calendar

month, day, year = map(int, input().split())
a = calendar.weekday(year, month, day)
d_name = list(calendar.day_name)
print(d_name[a].upper())

 08 05 2015


WEDNESDAY


## Time Delta

In [18]:
#!/bin/python3

import math
import os
import random
import re
import sys
from datetime import datetime

# Complete the time_delta function below.
def time_delta(t1, t2):
    # Parse the input time strings into timezone-aware datetime objects
    z_1=datetime.strptime(t1,"%a %d %b %Y %H:%M:%S %z")
    z_2=datetime.strptime(t2,"%a %d %b %Y %H:%M:%S %z")
    # We calculate the absolute difference in seconds and return it in a form of string
    return str(int(abs((z_1-z_2).total_seconds())))

    t = int(input())
    for t_itr in range(t):
        t1 = input()
        t2 = input()
        delta = time_delta(t1, t2)
        print(delta)


# Errors and Exceptions

## Exceptions

In [6]:
T = int(input())
for i in range(T):
    try:
        a, b = map(int, input().split())
        print(a//b)
    except ZeroDivisionError as e:
        print("Error Code:",e)
    except ValueError as e:
        print("Error Code:",e)
    

 3
 1 0


Error Code: integer division or modulo by zero


 2 $


Error Code: invalid literal for int() with base 10: '$'


 3 1


3


# Built-Ins

## Zipped!

In [11]:
n, x = map(int, input().split())
grades = []
for i in range(x):
    grades.append(list(map(float, input().split())))

zipl =list(zip(*grades))
 
for j in range(n):
    average = sum(list(zipl[j]))/x
    print(average)


 5 3
 89 90 78 93 80
 90 91 85 88 86
 91 92 83 89 90.5


90.0
91.0
82.0
90.0
85.5


## Athlete Sort

In [14]:
import math
import os
import random
import re
import sys



if __name__ == '__main__':
    nm = input().split()

    n = int(nm[0])

    m = int(nm[1])

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    k = int(input())
# Sort arr based on the k-th element of each row and print the result
for i in sorted(arr, key = lambda x : x[k]):
    print(' '.join(str(y) for y in i))

 5 3
 10 2 5
 7 1 0
 9 9 9
 1 23 12
 6 5 9
 1


7 1 0
10 2 5
6 5 9
9 9 9
1 23 12


## ginortS

In [17]:
s = sorted(input())
u=[]
l=[]
o=[]
e=[]

for i in s:
    if i.isalpha():
        if i.islower():
            a=l
        else:
            a=u
    else:
        if int(i)%2:
            a=o
        else:
            a=e
    a.append(i)

print("".join(l+u+o+e))


 Sorting1234


ginortS1324


# Python Functionals

## Map and Lambda Function

In [21]:
cube = lambda x: x**3 # complete the lambda function 

def fibonacci(n):
    a = [0, 1]
    if n == 0:
        return []
    if n == 1:
        return [0]
    for i in range(2, n):
        nums = a[-1] + a[-2]
        a.append(nums)
    return a

# Regex and Parsing

# Detect Floating Point Number

In [25]:
test = int(input())
for i in range(test):
    string = input()
    flag = True
    try:
        float_string = float(string)
        if string.count(".")==0:
            flag = False
    except:
        flag = False
    
    print(flag)

 4
 4.0O0


False


 -1.00


True


 +4.54


True


 SomeRandomStuff


False


## Re.split()

In [28]:
regex_pattern = r"[.,]"

## Group(), Groups() & Groupdict()

In [31]:
import re
s = input()
# Search for the first occurrence of a repeating character using regex
r = re.search(r'([a-zA-Z0-9])\1', s)
if r:
    print(r.group(1))
else:
    print(-1)

 12345678910111213141516171820212223


1


## Re.findall() & Re.finditer()

In [38]:
import re
s = input()
# We find all sequences of two or more consecutive vowels that are surrounded by consonants
r = re.findall(r'(?<=[^aeiouAEIOU])[aeiouAEIOU]{2,}(?=[^aeiouAEIOU])',s)
if r:
    for i in r:
        print(i)
else:
    print(-1)

 rabcdeefgyYhFjkIoomnpOeorteeeeet


ee
Ioo
Oeo
eeeee


## Re.start() & Re.end()

In [41]:
import re
s = input()
k = input()

def results(s, k):
    # Use regex to find all occurrences of the substring k in the string s
    same = re.finditer(fr'(?=({k}))', s)
    # Create a list of tuples containing the start and end indices of each match
    x = [(match.start(1), match.end(1)-1) for match in same]
    return x if x else [(-1, -1)]


if results(s, k):
    for i in results(s, k):
        print(i)
else:
    print((-1, -1))  

 aaadaa
 aa


(0, 1)
(1, 2)
(4, 5)


## Regex Substitution

In [44]:
import re
n = int(input())
for i in range(n):
  s = input()
  s = re.sub(r"(?<= )&&(?= )", "and", s)
  s = re.sub(r"(?<= )\|\|(?= )", "or", s)
  print(s)

 11
 a = 1;


a = 1;


 b = input();


b = input();


 if a + b > 0 && a - b < 0:


if a + b > 0 and a - b < 0:


 start()


start()


 elif a*b > 10 || a/b < 1:


elif a*b > 10 or a/b < 1:


 stop()


stop()


 print set(list(a)) | set(list(b))


print set(list(a)) | set(list(b))


 #Note do not change &&& or ||| or & or |


#Note do not change &&& or ||| or & or |


 #Only change those '&&' which have space on both sides.


#Only change those '&&' which have space on both sides.


 #Only change those '|| which have space on both sides.


#Only change those '|| which have space on both sides.


## Validating Roman Numerals

In [47]:
regex_pattern = r"^M{0,3}(CM|CD|D?C{0,3})(XC|XL|L?X{0,3})(IX|IV|V?I{0,3})$"

## Validating phone numbers

In [50]:
import re
n = int(input())
for i in range(n):
    s = input().strip()
    if re.match(r'^[789]\d{9}$', s):
        print("YES")
    else:
        print("NO")

 2
 9587456281


YES


 1252478965


NO


## Validating and Parsing Email Addresses

In [53]:
import email.utils
import re
n= int(input())
for i in range(n):
    add = email.utils.parseaddr(input())
    check = re.match(r'^[a-zA-Z][\w._-]+@[a-zA-Z]+\.[a-zA-Z]{1,3}$', add[1])
    if check:
        print(email.utils.formataddr(add))
    

 2
 DEXTER <dexter@hotmail.com>


DEXTER <dexter@hotmail.com>


 VIRUS <virus!@variable.:p>


## Hex Color Code

In [56]:
import re
n = int(input())
for i in range(n):
    CSS = input().strip()
    a = re.findall(r"(#[0-9a-fA-F]{3}|#[0-9a-fA-F]{6})(?=[;),])", CSS)
    if a :
        print(*a, sep="\n")

 11
 #BED
 {
 color: #FfFdF8; background-color:#aef;


#FfFdF8
#aef


 font-size: 123px;
 
 }
 #Cab
 {
 background-color: #ABC;


#ABC


 border: 2px dashed #fff;


#fff


 }


## HTML Parser - Part 1

In [62]:
from html.parser import HTMLParser
    
class MyHTMLParser(HTMLParser):
    def handle_starttag(self, tag, attrs):
        print("Start :", tag)
        self.print_tag_attrs(attrs=attrs)

    def handle_endtag(self, tag):
        print("End   :", tag)

    def handle_startendtag(self, tag, attrs):
        print("Empty :", tag)
        self.print_tag_attrs(attrs=attrs)
    
    def print_tag_attrs(self, attrs):
        [print(f"-> {i[0]} > {i[1]}") for i in attrs]

parser = MyHTMLParser()
parser.feed(''.join([input() for _ in range(int(input()))]))


 2
 <html><head><title>HTML Parser - I</title></head>
 <body data-modal-target class='1'><h1>HackerRank</h1><br /></body></html>


Start : html
Start : head
Start : title
End   : title
End   : head
Start : body
-> data-modal-target > None
-> class > 1
Start : h1
End   : h1
Empty : br
End   : body
End   : html


## HTML Parser - Part 2

In [65]:
from html.parser import HTMLParser

class MyHTMLParser(HTMLParser):
    def handle_comment(self, data):
        if "\n" not in data:
            print(">>> Single-line Comment")
        else:
            print(">>> Multi-line Comment")
        print(data)
    def handle_data(self, data):
        if i := data.rstrip():
            print(">>> Data")
            print(i)  

## Detect HTML Tags, Attributes and Attribute Values

In [68]:
from html.parser import HTMLParser

class MyHTMLParser(HTMLParser):
    def handle_starttag(self, tag, attrs):
        print(tag)
        if attrs:
            [print(f'-> {x[0]} > {x[1]}') for x in attrs]
    def handle_startendtag(self, tag, attrs):
        print(tag)
        if attrs:
            [print(f'-> {y[0]} > {y[1]}') for y in attrs]  
  
html = ""       
for i in range(int(input())):
    html += input().rstrip()
    html += '\n'
    
parser = MyHTMLParser()
parser.feed(html)
parser.close()


 9
 <head>
 <title>HTML</title>
 </head>
 <object type="application/x-flash"
 data="your-file.swf"
 width="0" height="0">
 <!-- <param name="movie" value="your-file.swf" /> -->
 <param name="quality" value="high"/>
 </object>


head
title
object
-> type > application/x-flash
-> data > your-file.swf
-> width > 0
-> height > 0
param
-> name > quality
-> value > high


## Validating UID

In [71]:
import re
check = r"^(?=([A-Z]*[a-z\d]){2})(?=([a-zA-Z]*[\d]){3})(([a-zA-Z0-9])(?!.*\4)){10}$"
t = int(input())
for i in range(t):
    uid = input()
    x = re.match(check, uid)
    if x:
        print("Valid")
    else:
        print("Invalid")

 2
 B1CD102354


Invalid


 B1CDEF2354


Valid


## Validating Credit Card Numbers

In [74]:
import re
n = int(input())
check = r"(?=[456]\d{3}(-?\d{4}){3}$)(?!.*(.)-?(\2-?){3})"
for i in range(n):
    cr = input()
    x = re.match(check, cr)
    if x:
        print("Valid")
    else:
        print("Invalid")
    

 6
 4123456789123456


Valid


 5123-4567-8912-3456


Valid


 61234-567-8912-3456


Invalid


 4123356789123456


Valid


 5133-3367-8912-3456


Invalid


 5123 - 3567 - 8912 - 3456


Invalid


## Validating Postal Codes

In [77]:
regex_integer_in_range = r"^([1-9][0-9]{5})$"	# Do not delete 'r'.
regex_alternating_repetitive_digit_pair = r"(?=(.)(.)(\1))"	# Do not delete 'r'.

## Matrix Script

In [20]:
import math
import os
import random
import re
import sys




first_multiple_input = input().rstrip().split()

n = int(first_multiple_input[0])

m = int(first_multiple_input[1])

matrix = []

for _ in range(n):
    matrix_item = input()
    matrix.append(matrix_item)

de = ""
for i in range(m):
    for j in range(n):
        de += matrix[j][i]
     

print(re.sub(r"(?<=[A-Za-z0-9])[^A-Za-z0-9]+(?=[A-Za-z0-9])", " ", de))        
        

 7 3
 Tsi
 h%x
 i #
 sM 
 $a 
 #t%
 ir!


This is Matrix#  %!


# XML

## XML 1 - Find the Score

In [3]:
def get_attr_number(node):
    counter = 0
    for i in node.iter():
        sc = len(i.attrib)
        counter += sc
    return counter

## XML2 - Find the Maximum Depth

In [6]:
maxdepth = 0
def depth(elem, level):
    global maxdepth
    level += 1
    if level > maxdepth:
        maxdepth = level
    for i in elem:
        depth(i, level)
    return maxdepth

# Closures and Decorators

# Standardize Mobile Number Using Decorators 

In [10]:
def wrapper(f):
    def fun(l):
        for i in range(len(l)):
            l[i] = "+91 " + l[i][-10:-5] + " " + l[i][-5:]
        f(l)
        
    return fun

## Decorators 2 - Name Directory 

In [13]:
def person_lister(f):
    def inner(people):
        return map(f, sorted(people, key=lambda x: int(x[2])))
    return inner

# Nympy

## Arrays

In [17]:
def arrays(arr):
    a = numpy.array(arr, float)
    return(a[::-1])

## Shape and Reshape 

In [20]:
import numpy



l = list(map(int, input().split()))

my_array = numpy.array(l)
print(numpy.reshape(my_array, (3,3)))

 1 2 3 4 5 6 7 8 9


[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Transpose and Flatten

In [23]:
import numpy

n_r, m_c = map(int, input().split())
arr = numpy.array([input().split() for i in range(n_r)], int)
print(numpy.transpose(arr))
print(arr.flatten())

 2 2
 1 2
 3 4


[[1 3]
 [2 4]]
[1 2 3 4]


## Concatenate

In [28]:
import numpy 

n_r, m_r, p_r = map(int, input().split())

arr_1 = numpy.array([[a for a in input().split()] for i in range(m_r)], int)
arr_2 = numpy.array([[b for b in input().split()] for i in range(n_r)], int)
con = numpy.concatenate((arr_1, arr_2), axis = 0)
print(con)

 4 3 2
  1 2
 1 2
 1 2
 1 2
 3 4
 3 4
 3 4


[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


## Zeros and Ones

In [31]:
import numpy as np

n = list(map(int, input().split()))
print(np.zeros(n, dtype = int))
print(np.ones(n, dtype = int))

 3 3 3


[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


## Eye and Identity

In [34]:
import numpy 
numpy.set_printoptions(legacy='1.13')

n_r, m_c = map(int,input().split())
print(numpy.eye(n_r, m_c, k=0))

 3 3


[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


## Array Mathematics

In [37]:
import numpy


n, m = map(int, input().split())
A = numpy.array([[j for j in input().split()] for i in range(n)], int)
B = numpy.array([[j for j in input().split()] for i in range(n)], int)
print(numpy.add(A,B))
print(numpy.subtract(A,B))
print(numpy.multiply(A,B))
print(numpy.floor_divide(A,B))
print(numpy.mod(A,B))
print(numpy.power(A,B))

 1 4
 1 2 3 4
 5 6 7 8


[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


## Floor, Ceil and Rint

In [40]:
import numpy
numpy.set_printoptions(legacy="1.13")

A = numpy.array(list(map(float, input().split())))
print(numpy.floor(A))
print(numpy.ceil(A))
print(numpy.rint(A))


 1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9


[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


## Sum and Prod

In [43]:
import numpy

n, m = map(int, input().split())
arr = numpy.array([list(map(int, input().split())) for i in range(n)])
sm = numpy.sum(arr, axis=0)
pr = numpy.prod(sm)
print(pr)

 2 2
 1 2
 3 4


24


## Min and Max

In [46]:
import numpy

n, m = map(int, input().split())
arr = numpy.array([list(map(int, input().split()))for i in range(n)])
mn = numpy.min(arr, axis=1)
print(numpy.max(mn))

 4 2
 2 5
 3 7
 1 3
 4 0


3


## Mean, Var, and Std

In [50]:
import numpy

n, m = map(int, input().split())
arr = numpy.array([list(map(int, input().split()))for i in range(n)])
print(numpy.mean(arr, axis=1))
print(numpy.var(arr, axis=0))
print(round(numpy.std(arr), 11)) # untile the 11th digit

 2 2
 1 2
 3 4


[ 1.5  3.5]
[ 1.  1.]
1.11803398875


## Dot and Cross

In [53]:
import numpy

n = int(input())
arr_A = numpy.array([list(map(int, input().split()))for i in range(n)])
arr_B = numpy.array([list(map(int, input().split()))for i in range(n)])
print(numpy.dot(arr_A, arr_B))

 2
 1 2
 3 4
 1 2
 3 4


[[ 7 10]
 [15 22]]


## Inner and Outer

In [56]:
import numpy

A = numpy.array(list(map(int, input().split())))
B = numpy.array(list(map(int, input().split())))
print(numpy.inner(A, B))
print(numpy.outer(A, B))

 0 1
 2 3


3
[[0 0]
 [2 3]]


## Polynomials

In [59]:
import numpy

p = list(map(float,input().split()))
x = int(input())
arr = numpy.polyval(p,x)
print(arr)

 1.1 2 3
 0


3.0


## Linear Algebra

In [62]:
import numpy

n = int(input())
arr = numpy.array([list(map(float, input().split()))for i in range(n)])
print(round(numpy.linalg.det(arr), 2)) # until the second digit

 2
 1.1 1.1
 1.1 1.1


0.0


# Challenges

## Birthday Cake Candles

In [22]:
import math
import os
import random
import re
import sys


#
# Complete the 'birthdayCakeCandles' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER_ARRAY candles as parameter.
#

def birthdayCakeCandles(candles):
    total = candles.count(max(candles))
    return total

    candles_count = int(input().strip())

    candles = list(map(int, input().rstrip().split()))

    result = birthdayCakeCandles(candles)

    print(result)



## Number Line Jumps

In [24]:
import math
import os
import random
import re
import sys

#
# Complete the 'kangaroo' function below.
#
# The function is expected to return a STRING.
# The function accepts following parameters:
#  1. INTEGER x1
#  2. INTEGER v1
#  3. INTEGER x2
#  4. INTEGER v2
#

def kangaroo(x1, v1, x2, v2):
    if (v1 - v2) == 0:
        return "NO"
    elif (x2-x1) / (v1 - v2) > 0 and ((x2-x1) / (v1 - v2)).is_integer():
        return "YES"
    else:
        return "NO"

    first_multiple_input = input().rstrip().split()

    x1 = int(first_multiple_input[0])

    v1 = int(first_multiple_input[1])

    x2 = int(first_multiple_input[2])

    v2 = int(first_multiple_input[3])

    result = kangaroo(x1, v1, x2, v2)

    print(result)


## Viral Advertising

In [26]:
import math
import os
import random
import re
import sys

#
# Complete the 'viralAdvertising' function below.
#
# The function is expected to return an INTEGER.
# The function accepts INTEGER n as parameter.
#

def viralAdvertising(n):
    cumulative = 0
    liked = 5//2
    
    for i in range(n):
        cumulative += liked
        liked = (liked*3)//2
    
    return cumulative

    n = int(input().strip())

    result = viralAdvertising(n)
    print(result)



## Recursive Digit Sum

In [31]:
import math
import os
import random
import re
import sys

#
# Complete the 'superDigit' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. STRING n
#  2. INTEGER k
#

def superDigit(n, k):
    total = 0
    if len(n) <= 1:
        return n
    else:
        total = k*sum([int(i) for i in n])
        return superDigit(str(total), 1)

    first_multiple_input = input().rstrip().split()

    n = first_multiple_input[0]

    k = int(first_multiple_input[1])

    result = superDigit(n, k)

    print(result)


## Insertion Sort - Part 1

In [13]:
import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort1' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def insertionSort1(n, arr):
    value = arr[-1]
    i = n - 2
    while i >= 0 and arr[i] > value:
        arr[i + 1] = arr[i]
        print(*arr)
        i -= 1
        
    arr[i + 1] = value
    print(*arr)
            
        

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort1(n, arr)


 5
 2 4 6 8 3


2 4 6 8 8
2 4 6 6 8
2 4 4 6 8
2 3 4 6 8


## Insertion Sort - Part 2

In [16]:
import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort2' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def insertionSort2(n, arr):
    for i in range(1, n):
        j = i
        while j > 0 and arr[j-1] > arr[j]:
            arr[j-1], arr[j] = arr[j], arr[j-1]
            j = j - 1
        else:
            print(*arr, sep=" ")
            
    return arr 

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort2(n, arr)


 6
 1 4 3 5 6 2


1 4 3 5 6 2
1 3 4 5 6 2
1 3 4 5 6 2
1 3 4 5 6 2
1 2 3 4 5 6
